### ISSUE TITLE
Expose `provider` 

### ISSUE THREAD

**Issue by pi0** [unjs/std-env#12]
(initial idea from @ascorbic) we can expose `provider` (maybe) by using [`ci-info`](https://github.com/watson/ci-info) that is already a dependency. 

Additional environment variables that need either PR to ci-info's upstream or local patch:

- `NETLIFY_LOCAL`
- `INPUT_AZURE_STATIC_WEB_APPS_API_TOKEN` (/cc @danielroe we don't have normal `AZURE_PIPELINES` in azure static right?)
- Cloudflare pages (TODO: Ask or check if there is any) 
- Docker

**Comment by ascorbic** [comment]
`NETLIFY_LOCAL` would also be a special case because it's not CI

**Comment by pi0** [comment]
Good point! So maybe we call it `platform` or `environment`? (initially suggested `target` makes sense in nuxt-nitro context but I think from `std-env` it can be something more relevant. any ideas welcome)

**Comment by ascorbic** [comment]
I spent ages trying to think what would be a good name! Platform sounds like it should be linux, darwin etc. Environment makes me think node, electron, browser. I thought host but that could mean hostname! Provider is one option. Service is another.

**Comment by pi0** [comment]
I like `provider`!

**Comment by pi0** [comment]
Implemented in 3.0.0-0 rewrite. Feel free to make PR for improvements.
