### ISSUE TITLE
Cannot find module './node_modules/std-env/dist/index.cjs'

### ISSUE THREAD

**Issue by tm1000** [unjs/std-env#24]
Looks like you no longer build the commonjs file. Though you list it in package.json

You can see from the release of 3.1.0: https://registry.npmjs.org/std-env/-/std-env-3.1.0.tgz

The dist folder has no cjs.

**Comment by finndev** [comment]
Same error here.

```
[webpack-cli] Error: Cannot find module '~/Code/XXXX/node_modules/std-env/dist/index.cjs'
```

**Comment by pi0** [comment]
Sorry for the regression! Please update lock file in order to use `std-env@3.1.1` or later.

**Comment by tm1000** [comment]
Thanks it works!
