### ISSUE TITLE
Add Cloudflare Pages environment

### ISSUE THREAD

**Issue by DaniFoldi** [unjs/std-env#30]
Cloudflare Pages projects can be built automatically by Cloudflare after pushing to a git repository. In this case, their build system does not set the `CI` env variable, instead they use `CF_PAGES` (and some others).

Docs: https://developers.cloudflare.com/pages/platform/build-configuration/#environment-variables

**Comment by pi0** [comment]
Can you please open a PR to add to [providers.ts](https://github.com/unjs/std-env/blob/main/src/providers.ts)? 🙏🏼 I think we can call it `cloudflare_pages`

**Comment by DaniFoldi** [comment]
@pi0 I believe #31 is ready for a review
