### ISSUE TITLE
Support static `NODE_ENV` detection

### ISSUE THREAD

**Issue by pi0** [unjs/std-env#45]
In some environments (like nuxt builds with vite/webpack and nitropack) `process.env.NODE_ENV` is statically replaced. This makes `std-env` not working as expected. We might use an inline syntax instead that get's replaced.

E2E reproduction:

https://stackblitz.com/edit/nuxt-starter-7oay4d?file=components%2Fapp-config-client.client.vue,components%2Fapp-config-server.server.vue,app.vue,nuxt.config.ts,app.config.ts,components%2Fapp-config-api.vue,server%2Fapi%2Fapp-config.ts

**Comment by peterbud** [comment]
Hi @pi0  - has this been fixed in 3.3.3? Using the above repro, updating to std-env 3.3.3 and latest nuxt, I still get `isDevelopment` false in CSR.

**Comment by pi0** [comment]
Followup https://github.com/nuxt/nuxt/issues/21313

**Comment by peterbud** [comment]
Thanks for the follow up! 👍
