### ISSUE TITLE
Integrate runtime detection

### ISSUE THREAD

**Issue by QuiiBz** [unjs/std-env#65]
### Describe the feature

I've created [detect-runtime](https://github.com/QuiiBz/detect-runtime) a few months ago as a way to detect the current JavaScript runtime where the code is running. As Atinux suggested, we could bring this feature to std-env, which could be a great fit.

detect-runtime follows the [WinterCG](https://wintercg.org/) [Runtime Keys specification](https://runtime-keys.proposal.wintercg.org/), which sometimes duplicate the same underlying JavaScript runtime (`edge-light` is technically `workerd`, `netlify` is technically `deno`). Do we also want to follow this specification, or instead use a subset? (`node`, `deno`, `bun`, `workerd`, `lagon`, `fastly`)

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
Thanks for creating the issue. I think it is a brilliant idea to add flags to detect runtime environments as well.

Currently, we detect "platforms" mainly for CI environments. We can extend it for runtimes as well from [here](https://github.com/unjs/std-env/blob/main/src/providers.ts#L125) using a new Array.

I think platform names following runtime key consistency makes the most sense as platforms usually have specific setup and behavior.

We shall also export more flags (from `flags.ts`) for `isNode,` isBun`, `isDeno`, etc indicating actual runtime.

Feel free to draft a PR 💯
