### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'bun')

### ISSUE THREAD

**Issue by peterbud** [unjs/std-env#75]
### Environment

browser, edge

### Reproduction

Upgrading from 3.3.3 to 3.4.2 

### Describe the bug

After upgrading from 3.3.3 to 3.4.2 I get this error upon starting the nuxt app: 
`Uncaught TypeError: Cannot read properties of undefined (reading 'bun') at index.mjs:1:2785`

Reverting back to 3.3.3: no issues anymore

**Comment by pi0** [comment]
Thanks for report. Should be solved in 3.4.3

**Comment by peterbud** [comment]
Wow, that's what I call lightspeed! Many thanks
