### ISSUE TITLE
Document the environment variables in the README

### ISSUE THREAD

**Issue by Soviut** [unjs/std-env#9]
I'm developing a Nuxt application inside a Docker container with a TTY connection tailing the logs. The fancy progress bars on build do not always render correctly so I wanted to disable them.

I wound up doing it the hard way by overriding the progress bar plugins in the webpack config, see [here](https://github.com/nuxt/nuxt.js/issues/8844).

I only learned after the fact that the `minimalCLI` (which Nuxt uses to determine `basic` or `fancy` progress bars in the CLI) has environment variables that can force certain modes (eg: `MINIMAL=1`).

It would be really good to document the environment variables in the README.

**Comment by pi0** [comment]
I love the idea of also generally document how each detection is working

**Comment by pi0** [comment]
Added JSDocs for v3 explaining each flag.
